title: Dial Your Espresso
description: Track and perfect your espresso shots
url: https://orve90.github.io
baseurl: "/espresso-logger"

markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

exclude:
  - README.md
